FROM node:lts-alpine
WORKDIR /usr/src/app

ARG _CDN_CLOUD_NAME
ARG _CDN_API_KEY
ARG _CDN_API_SECRET
ARG _JWT_KEY
ARG _MONGO_URI

ENV CDN_CLOUD_NAME $_CDN_CLOUD_NAME
ENV CDN_API_KEY $_CDN_API_KEY
ENV CDN_API_SECRET $_CDN_API_SECRET
ENV JWT_KEY $_JWT_KEY
ENV MONGO_URI $_MONGO_URI

COPY . .

RUN npm install && npm run build

EXPOSE 8080

CMD npm run start

