FROM node:lts-alpine
WORKDIR /usr/src/app

ARG _CDN_CLOUD_NAME
ARG _CDN_API_KEY
ARG _CDN_API_SECRET
ARG _MONGO_URI
ARG _TEST_ENV

ENV CDN_CLOUD_NAME $_CDN_CLOUD_NAME
ENV CDN_API_KEY $_CDN_API_KEY
ENV CDN_API_SECRET $_CDN_API_SECRET
ENV MONGO_URI $_MONGO_URI
ENV TEST_ENV $_TEST_ENV

COPY . .

RUN npm install && npm run build

EXPOSE 8080

CMD npm run start

